import numpy as np
import math

class WindEnergyModel:
    def __init__(self, alpha, C_p, V_ci, V_co, V_rated, P_rated, D, H_m, V0):
        self.alpha = alpha
        self.C_p = C_p
        self.V_ci = V_ci
        self.V_co = V_co
        self.V_rated = V_rated
        self.P_rated = P_rated
        self.D = D
        self.H_m = H_m
        self.V0 = V0

    def wind_power(self):
        """
        This function calculates the wind power generated by the wind turbine.
        """
        #assumptions:
        #onshore
        #Horizontal Axis Wind Turbine (HAWT)
        #locate on Bleiswijk
        #upstream wind speed equal to wind speed
        #1kts = 0.5144m/s
        #variable speed wind turbine
        #current use 
        #hourly data for wind speed in KNMI

        #parameters (static)
        rho_0 = 1.225 # kg/m^3, density of air at atmospheric pressure
        #Angular_s = 200 #rad/s, angular speed of the wind turbine # chanege with wind speed or not
        H_0 = 10 #m, standard for weather forcast

        #alpha = 0.2 #power-law exponent, ref:https://www.mdpi.com/1996-1073/12/10/1907
        #C_p = 0.5 #maximum power coefficeint, concept ref: https://www.sciencedirect.com/science/article/pii/S1364032113000439#bib12; loss value ref
        #V_ci = 2 #m/s, cut-in wind speed, ref:https://www.sciencedirect.com/science/article/pii/S1364032113000439#bib24 Appendix B
        #V_co = 28#m/s, cut-out wind speed, ref:https://www.sciencedirect.com/science/article/pii/S1364032113000439#bib24 Appendix B
        #V_rated = 12.4#m/s, rated wind speed, ref:https://www.sciencedirect.com/science/article/pii/S1364032113000439#bib24 Appendix B
        #P_rated = 2e6 #W, rated power, same ref above
        #D = 82#m, rotor diameter, same ref above
        
        #parameters (dynamic)
        #H_m = 80 #m, hub height of onshore wind turbines, ref:https://www.mdpi.com/1996-1073/15/1/302
        #D = 60 #m, rotor diameter
        #V_u = 3 #m/s, upstream wind velocity
        #S_wind = 3 #m/s, wind speed at hub height

        #main equation
        #V0_m = self.V0 * 0.5144 #convert kts to m/s
        rho_air = rho_0 * np.exp(-((0.29/3048) * self.H_m)) #kg/m^3
        A_wind = math.pi * (self.D**2/4) #swept area of blades, m^2 （D/2）**2
        V_wind = (self.H_m/H_0) ** self.alpha * self.V0 #wind speed at hub height, m/s
        #V_u = V_wind
        #to do: the relationship between Angular_s and wind speed
        #V_d = (Angular_s * 0.5 * D) / V_wind
        #lamda = V_d / V_wind #V_u #tip speed ratio of the wind turbine
        #C_p = (1 + lamda) * (1 - lamda**2) * 0.5 #fraction of upstream wind power captured by the rotor blades

        #P = 0.5 * rho_air * A_wind * V_u**3 * C_p
        P_cal = 0.5 * rho_air * A_wind * V_wind**3 * self.C_p

        #if V_wind < self.V_ci or V_wind > self.V_co:
            #P = 0 #power is zero outside of cut-in and cut-out wind speeds
        #elif V_wind >= self.V_ci and V_wind < self.V_rated:
            #P = P_cal
        #elif V_wind >= self.V_rated and V_wind <= self.V_co:
            #P = self.P_rated
        
        if V_wind < self.V_ci:
            P = 0 #power is zero outside of cut-in and cut-out wind speeds
        elif V_wind < self.V_rated:
            #P = P_cal
            P = min(P_cal, self.P_rated)
        elif V_wind <= self.V_co:
            P = self.P_rated
        else:
            #print(f"V_wind: {V_wind}, Cut-out: {self.V_co}")
            P = 0

        #if P_cal > 2e6:
            #print("error: P_cal is greater than 2e6")

        #print("P_cal:", P_cal)
        #print("rho_air:", rho_air)

        return P


